# Generated by Django 4.0.5 on 2022-06-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakersd', '0002_alter_speaker_available_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
